# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

arcDist <- function(x, y, r) {
    .Call('_levelnet_arcDist', PACKAGE = 'levelnet', x, y, r)
}

arcDistMat <- function(X, r) {
    .Call('_levelnet_arcDistMat', PACKAGE = 'levelnet', X, r)
}

choose <- function(n, k) {
    .Call('_levelnet_choose', PACKAGE = 'levelnet', n, k)
}

hypergeom <- function(P, deg, m) {
    .Call('_levelnet_hypergeom', PACKAGE = 'levelnet', P, deg, m)
}

isBipartite <- function(G, V, src) {
    .Call('_levelnet_isBipartite', PACKAGE = 'levelnet', G, V, src)
}

