# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getA_cpp <- function(x, y) {
    .Call('_levelnet_getA_cpp', PACKAGE = 'levelnet', x, y)
}

mse <- function(adjList, deg) {
    .Call('_levelnet_mse', PACKAGE = 'levelnet', adjList, deg)
}

isBipartite <- function(G, V, src) {
    .Call('_levelnet_isBipartite', PACKAGE = 'levelnet', G, V, src)
}

scobit_loglike_cpp <- function(x1, x2, y, params) {
    .Call('_levelnet_scobit_loglike_cpp', PACKAGE = 'levelnet', x1, x2, y, params)
}

scobit_loglike_gr_cpp <- function(x1, x2, y, params) {
    .Call('_levelnet_scobit_loglike_gr_cpp', PACKAGE = 'levelnet', x1, x2, y, params)
}

